version: "3"

services:
  # start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: concurrency
    # Mount /var/lib/postgresql/data in docker to the ./db-data/postgres in my localhost
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  # start Redis, and ensure that data is stored to a mounted volume
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
    # Mount /data to ./db-data/redis/
    volumes:
      - ./db-data/redis/:/data

  # start mailhog
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
